spring.application.name=crud

spring.threads.virtual.enabled=true

spring.datasource.hikari.connection-timeout=2000

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
